name: Build

env:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    
    # NUGET_AUTH_TOKEN environment variable is required to access other nuget packages in private github repositories.
    # The variable is set from repository secrects. The token can be created in https://github.com/settings/tokens and then added to the repository secrets.
    # Private repository source must be added to setup stage with `source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json`.
    NUGET_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
    
on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: src

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0    

    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x            
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

    - name: Restore
      run:
        dotnet restore

    - name: Build
      run: dotnet build --no-restore -nologo -c:Release

    - name: Version
      run: |  
        dotnet tool install --global GitVersion.Tool --version 5.8.1
        dotnet gitversion /output buildserver 
        
    - name: Pack
      working-directory: .
      run: |
        nuget pack .nuspec -NoDefaultExcludes -OutputDirectory bin -Version ${{ env.GitVersion_FullSemVer }}
 
    - name: Push    
      working-directory: .
      # Push to github 
      run: dotnet nuget push "bin/*.nupkg" -k ${{ secrets.PACKAGES_TOKEN }} -s https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --skip-duplicate

